// Generated by https://quicktype.io

export interface Administrador {
    _id?:        string;
    nombre:     string;
    nusuario:   string;
    correo:     string;
    contrasena: string;
    estado?:     boolean;
    __v?:        number;
}
