version: '3'

services:
  monolitico:
  # Carpeta del monolitico
    build: ./monolitico
  usuarios:
  # Carpeta del usuarios
    build: ./microservicios/usuarios
  # Carpeta del productos
  productos:
    build: ./microservicios/productos
  # Carpeta del clientes
  clientes:
    build: ./microservicios/clientes

  nginx: 
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolitico
      - usuarios
      - productos
      - clientes